### ISSUE TITLE
Update to Ubuntu 22.04 LTS (and POP OS 22.04)

### ISSUE THREAD

**Issue by Lapazlane** [Slimbook-Team/slimbookface#9]
Hello, this enables my Thinkpad Yoga 370 to use face log in (it lacks an IR sensor) - will you be updating for Ubuntu (etc) 22.04 LTS? I'm holding off updating until I can use slimbookface. Thank you for your work on this.

**Comment by slimbook** [comment]
Yes, we will update as soon as we can, thank you for your patience.
